server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ltm_demo
    username: postgres
    password: 1234
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update

token:
  secretKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
  expirationTime:
    access: 864000000
    refresh: 12096000000
open:
  api:
    title: API for network programming
    version: v1.0.0
    description: demo
    serverUrl: http://localhost:${server.port}
    serverName: server dev
